version: '3.8'

services:
  # FastAPI Backend
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=password
    volumes:
      - ./data:/app/data
      - ./vector_store:/app/vector_store
      - ./logs:/app/logs
    depends_on:
      - neo4j
    networks:
      - medical-rag-network

  # Neo4j Knowledge Graph (Optional)
  neo4j:
    image: neo4j:5.12
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - medical-rag-network

  # Frontend (Optional - simple HTTP server)
  frontend:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    networks:
      - medical-rag-network

volumes:
  neo4j_data:
  neo4j_logs:

networks:
  medical-rag-network:
    driver: bridge
